//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Devlosys.Resources.I18N {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfigResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigResource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apps.Devlosys.Resources.I18N.ConfigResource", typeof(ConfigResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Barflow server.
        /// </summary>
        public static string BarflowServerHintServer {
            get {
                return ResourceManager.GetString("BarflowServerHintServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BIN.
        /// </summary>
        public static string BinHintText {
            get {
                return ResourceManager.GetString("BinHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Double check.
        /// </summary>
        public static string DoubleCheckText {
            get {
                return ResourceManager.GetString("DoubleCheckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string FTPPasswordHintText {
            get {
                return ResourceManager.GetString("FTPPasswordHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ftp username.
        /// </summary>
        public static string FTPUsernameHintText {
            get {
                return ResourceManager.GetString("FTPUsernameHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à iTAC FVT interlock.
        /// </summary>
        public static string ITACFVTInterlockText {
            get {
                return ResourceManager.GetString("ITACFVTInterlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ITAC Interlocking.
        /// </summary>
        public static string ITACInterlockingText {
            get {
                return ResourceManager.GetString("ITACInterlockingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ITAC Server.
        /// </summary>
        public static string ItacServerHintText {
            get {
                return ResourceManager.GetString("ItacServerHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Labling station name.
        /// </summary>
        public static string LablingStationHintText {
            get {
                return ResourceManager.GetString("LablingStationHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Leak Hours.
        /// </summary>
        public static string LeakHoursHintText {
            get {
                return ResourceManager.GetString("LeakHoursHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MES Activation.
        /// </summary>
        public static string MESActivationText {
            get {
                return ResourceManager.GetString("MESActivationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MES shipping.
        /// </summary>
        public static string MESShippingHeaderText {
            get {
                return ResourceManager.GetString("MESShippingHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Serail port.
        /// </summary>
        public static string PortHintText {
            get {
                return ResourceManager.GetString("PortHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print manuelle label.
        /// </summary>
        public static string PrintManuelleLabelText {
            get {
                return ResourceManager.GetString("PrintManuelleLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print method.
        /// </summary>
        public static string PrintMethodText {
            get {
                return ResourceManager.GetString("PrintMethodText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Projets configuration.
        /// </summary>
        public static string ProjetsConfigHeaderText {
            get {
                return ResourceManager.GetString("ProjetsConfigHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quality validation.
        /// </summary>
        public static string QualityValidationText {
            get {
                return ResourceManager.GetString("QualityValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shipping printer.
        /// </summary>
        public static string ShippingPrinterHintText {
            get {
                return ResourceManager.GetString("ShippingPrinterHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current station name.
        /// </summary>
        public static string StationHintText {
            get {
                return ResourceManager.GetString("StationHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Station params.
        /// </summary>
        public static string StationParamsHeaderText {
            get {
                return ResourceManager.GetString("StationParamsHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration.
        /// </summary>
        public static string TitelText {
            get {
                return ResourceManager.GetString("TitelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Upload method.
        /// </summary>
        public static string UploadMethodText {
            get {
                return ResourceManager.GetString("UploadMethodText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Work center.
        /// </summary>
        public static string WorkCenterHintText {
            get {
                return ResourceManager.GetString("WorkCenterHintText", resourceCulture);
            }
        }
    }
}
