//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Devlosys.Resources.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DoubleCheckResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DoubleCheckResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apps.Devlosys.Resources.I18N.DoubleCheckResource", typeof(DoubleCheckResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAZE required to qulity validation because high number of check pcb with datamatrix captured!.
        /// </summary>
        public static string BlockMessage {
            get {
                return ResourceManager.GetString("BlockMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of check Riched.
        /// </summary>
        public static string BlockTitle {
            get {
                return ResourceManager.GetString("BlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label content.
        /// </summary>
        public static string ContentHint {
            get {
                return ResourceManager.GetString("ContentHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label doesnt match with the Laser datamatrix .
        ///You have only {0} for scanne correct data!.
        /// </summary>
        public static string ContentNotMatchMessage {
            get {
                return ResourceManager.GetString("ContentNotMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label verification.
        /// </summary>
        public static string HeaderText {
            get {
                return ResourceManager.GetString("HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to scanne the laser marking first ..
        /// </summary>
        public static string LaserEmptyMessage {
            get {
                return ResourceManager.GetString("LaserEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser marking.
        /// </summary>
        public static string LaserMarkingHint {
            get {
                return ResourceManager.GetString("LaserMarkingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This serial number {0} doesn&apos;t match the label of the pcba printed.
        /// </summary>
        public static string LaserNotMatchMessage {
            get {
                return ResourceManager.GetString("LaserNotMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curent laser scanned.
        /// </summary>
        public static string LaserScannedHint {
            get {
                return ResourceManager.GetString("LaserScannedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the first panel SN to proceed.
        /// </summary>
        public static string ScanPanelSNHint {
            get {
                return ResourceManager.GetString("ScanPanelSNHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning you have only 3 times to scan and check the PCBA with label.
        /// </summary>
        public static string SubHeaderText {
            get {
                return ResourceManager.GetString("SubHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in : {0} scanne.
        /// </summary>
        public static string TestNumberText {
            get {
                return ResourceManager.GetString("TestNumberText", resourceCulture);
            }
        }
    }
}
